$ANSIBLE_VAULT;1.1;AES256
65623765373264623566303635373330623537303831343231396362323435626135623861616632
3266333539303033636438356563373432323164643732650a363664373639663238643037386135
37626530653736653437396166373364356437393338343632316537306536356662383239666436
3933353537316539390a616634306430643464616236313730323764303832346333663936636663
30323666363763363263323631363930646139623735363531643662623966633134373165383230
64653464303030656137343265623366656635626338323837363664616437643736326566373061
32373330623535373364316538633031386231646531383565616132343537636138633333323465
66613664353764656332616433623239303864343466336433646434623233363866336566383139
37626661653862623666626237353666626161633238373336383061353562366263613036373538
33663634333739386233333836356136616231636332623737623165656633656339343032333732
32663862643535326564326566336564646165363438376561616232653864383762656432353234
35386236646435373434
